# Generated by Django 4.0.6 on 2024-04-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medical_specialty',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
